name: Java CI with JaCoCo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and Test
        run: mvn clean install

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco
          path: target/site/jacoco